services:
  # Project setup (unchanged)
  project-setup:
    image: michaelirwin244/workshop-poc:setup
    volumes:
      - project:/project
    environment:
      PROJECT_CLONE_URL: https://github.com/mikesir87/workshop-poc-content

  # React Frontend  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "8080:80"
    depends_on:
      workspace:
        condition: service_healthy  # Wait for workspace to be healthy
      backend:
        condition: service_started
    restart: unless-stopped
    labels:
      - demo-setup=true
    environment:
      - NODE_ENV=production
    networks:
      - default

  # Express Backend with swappable file system adapters
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-backend
    ports:
      - "8000:8000"
    volumes:
      - project:/project
      - socket-proxy:/var/run
      - /var/run/docker.sock:/var/run/docker.sock  # For container adapter
    environment:
      - NODE_ENV=production
      - WORKSPACE_ROOT=/project/workspace
      - TARGET_CONTAINER=workspace
      - CONTENT_DIR=/project/docs
    depends_on:
      project-setup:
        condition: service_completed_successfully
    restart: unless-stopped
    labels:
      - demo-setup=true
    networks:
      - default

  # Legacy instructions server (for backward compatibility)
  instructions:
    image: michaelirwin244/workshop-poc:markdown-server
    ports:
      - "8001:3000"
    volumes:
      - project:/project
    environment:
      ROOT_DIR: /project/docs
      SITE_TITLE: Workshop POC
    depends_on:
      project-setup:
        condition: service_completed_successfully
    labels:
      - demo-setup=true
    networks:
      - default

  # VS Code workspace - Add health check and start independently
  workspace:
    image: michaelirwin244/workshop-poc:workspace
    command: /home/coder/project
    depends_on:
      project-setup:
        condition: service_completed_successfully
      socket-proxy:
        condition: service_started
    ports:
      - "8085:8085"
      - "3001:3000"  # Changed from 3000 to avoid conflict
    environment:
      TESTCONTAINERS_HOST_OVERRIDE: localhost
    volumes:
      - socket-proxy:/var/run
      - type: volume
        source: project
        target: /home/coder/project
        volume:
          nocopy: true
          subpath: workspace
    labels:
      - demo-setup=true
    # Add health check to ensure VS Code is ready before other services depend on it
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/healthz", "||", "curl", "-f", "http://localhost:8085"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - default

  # Host port forwarding - Start AFTER workspace is healthy and use different network approach
  host-forwarding:
    image: michaelirwin244/workshop-poc:host-port-republisher
    volumes:
      - socket-proxy:/var/run
    # Remove network_mode to avoid conflicts - use port mapping instead
    environment:
      LABEL_FILTER: demo-setup=true
      # Add environment variable to connect to workspace container by name
      WORKSPACE_CONTAINER_NAME: workspace-1
    depends_on:
      workspace:
        condition: service_healthy  # Wait for workspace to be fully ready
      socket-proxy:
        condition: service_started
    labels:
      - demo-setup=true
    restart: unless-stopped
    networks:
      - default

  # Workspace cleaner - FORCE REBUILD to get package.json fix
  workspace-cleaner:
    build:
      context: ./support/workspace-cleaner
      dockerfile: Dockerfile
      no_cache: true  # Force no cache
    volumes:
      - socket-proxy:/var/run
    environment:
      LABEL_FILTER: demo-setup=true
    depends_on:
      socket-proxy:
        condition: service_started
    labels:
      - demo-setup=true
    networks:
      - default
    restart: unless-stopped

  # Socket proxy - Updated network configuration
  socket-proxy:
    image: mikesir87/docker-socket-proxy
    volumes:
      - socket-proxy:/tmp/proxy
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEBUG_LOGS: "true"
      CONFIG_DATA: |
        mutators:
          # Remap the project directory to the project volume, since the project
          # is running out of a volume.
          - type: mountPath
            from: /home/coder/project
            to: project/workspace

          # If requests to use the Docker Socket are used (such as Testcontainers),
          # use the proxied one to ensure permissions, remappings, etc. are applied
          - type: mountPath
            from: /var/run/docker.sock
            to: socket-proxy/docker.sock

          # Add labels to all newly created objects
          - type: addLabels
            labels:
              demo-setup: "true"

          - type: addToNetwork
            networks:
              - workshop-poc-infra_default
        gates:
          - type: mountSource
            allowedSources:
              - project
              - socket-proxy
              - buildx_buildkit_default_state

        responseFilters:
          # Only return objects with the labels we mutated on
          - type: labelFilter
            requiredLabels:
              demo-setup: "true"
      LISTEN_SOCKET_PATH: /tmp/proxy/docker.sock
    labels:
      - demo-setup=true
    networks:
      - default
    restart: unless-stopped

volumes:
  socket-proxy:
    name: socket-proxy
    labels:
      - demo-setup=true
  project:
    name: project
    labels:
      - demo-setup=true

# Use default network with specific name to match socket-proxy configuration
networks:
  default:
    name: workshop-poc-infra_default
    labels:
      - demo-setup=true
