services:
  app:
    build:
      context: ./
      target: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/local/app/src
